# Generated by Django 5.0.4 on 2024-08-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created_date_time']},
        ),
    ]
