# Generated by Django 5.0.4 on 2024-05-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_tag_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date_time']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created',
            new_name='date_time',
        ),
    ]
