# Generated by Django 5.0.4 on 2024-07-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_time',
            new_name='created_date_time',
        ),
    ]
