# Generated by Django 5.0.4 on 2024-08-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_options_review_owner'),
        ('users', '0008_alter_profile_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
