# Generated by Django 5.0.4 on 2024-08-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
